package it.giovanni.hub.ui.theme

import androidx.compose.ui.graphics.Color

val hubLightPrimary = Color(0xFF2B5BB5)
val hubLightOnPrimary = Color(0xFFFFFFFF)
val hubLightPrimaryContainer = Color(0xFFD9E2FF)
val hubLightOnPrimaryContainer = Color(0xFF001945)
val hubLightSecondary = Color(0xFF575E71)
val hubLightOnSecondary = Color(0xFFFFFFFF)
val hubLightSecondaryContainer = Color(0xFFDCE2F9)
val hubLightOnSecondaryContainer = Color(0xFF141B2C)
val hubLightTertiary = Color(0xFF235FA6)
val hubLightOnTertiary = Color(0xFFFFFFFF)
val hubLightTertiaryContainer = Color(0xFFD5E3FF)
val hubLightOnTertiaryContainer = Color(0xFF001B3C)
val hubLightError = Color(0xFFBA1A1A)
val hubLightOnError = Color(0xFFFFFFFF)
val hubLightErrorContainer = Color(0xFFFFDAD6)
val hubLightOnErrorContainer = Color(0xFF410002)
val hubLightOutline = Color(0xFF757780)
val hubLightBackground = Color(0xFFFEFBFF)
val hubLightOnBackground = Color(0xFF1B1B1F)
val hubLightSurface = Color(0xFFFBF8FD)
val hubLightOnSurface = Color(0xFF1B1B1F)
val hubLightSurfaceVariant = Color(0xFFE1E2EC)
val hubLightOnSurfaceVariant = Color(0xFF44464F)
val hubLightInverseSurface = Color(0xFF303034)
val hubLightInverseOnSurface = Color(0xFFF2F0F4)
val hubLightInversePrimary = Color(0xFFB0C6FF)
val hubLightSurfaceTint = Color(0xFF2B5BB5)
val hubLightOutlineVariant = Color(0xFFC5C6D0)
val hubLightScrim = Color(0xFF000000)

val hubDarkPrimary = Color(0xFFB0C6FF)
val hubDarkOnPrimary = Color(0xFF002D6F)
val hubDarkPrimaryContainer = Color(0xFF00429C)
val hubDarkOnPrimaryContainer = Color(0xFFD9E2FF)
val hubDarkSecondary = Color(0xFFC0C6DC)
val hubDarkOnSecondary = Color(0xFF293042)
val hubDarkSecondaryContainer = Color(0xFF404659)
val hubDarkOnSecondaryContainer = Color(0xFFDCE2F9)
val hubDarkTertiary = Color(0xFFA7C8FF)
val hubDarkOnTertiary = Color(0xFF003061)
val hubDarkTertiaryContainer = Color(0xFF004788)
val hubDarkOnTertiaryContainer = Color(0xFFD5E3FF)
val hubDarkError = Color(0xFFFFB4AB)
val hubDarkOnError = Color(0xFF690005)
val hubDarkErrorContainer = Color(0xFF93000A)
val hubDarkOnErrorContainer = Color(0xFFFFDAD6)
val hubDarkOutline = Color(0xFF8F9099)
val hubDarkBackground = Color(0xFF1B1B1F)
val hubDarkOnBackground = Color(0xFFE3E2E6)
val hubDarkSurface = Color(0xFF121316)
val hubDarkOnSurface = Color(0xFFC7C6CA)
val hubDarkSurfaceVariant = Color(0xFF44464F)
val hubDarkOnSurfaceVariant = Color(0xFFC5C6D0)
val hubDarkInverseSurface = Color(0xFFE3E2E6)
val hubDarkInverseOnSurface = Color(0xFF1B1B1F)
val hubDarkInversePrimary = Color(0xFF2B5BB5)
val hubDarkSurfaceTint = Color(0xFFB0C6FF)
val hubDarkOutlineVariant = Color(0xFF44464F)
val hubDarkScrim = Color(0xFF000000)

val seed = Color(0xFF0D47A1)